homeassistant:
  name: Умная квартира на Авиационной 10

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

lovelace:
  mode: yaml

# Text to speech
tts:
  - platform: google_translate

# Вынос во внешние файлы
group: !include includes/groups.yaml
automation: !include includes/automations.yaml
script: !include includes/scripts.yaml
scene: !include includes/scenes.yaml
recorder: !include includes/recorder.yaml
yeelight: !include includes/yeelight.yaml

# Вынос во внешние папки
sensor: !include_dir_merge_list includes/sensor

xiaomi_aqara:
  discovery_retry: 20
  gateways:
    - mac: 7C:49:EB:89:1A:1B
      key: nzeq72w4z794rhpa
      host: 192.168.0.52

