title: Home Assistant - Сервер
views:

  - title: Телевизор
    icon: mdi:television
              
    cards:
    
      - type: vertical-stack
        cards:
        - type: markdown
          content: >
             **Панель переключателей**
              
        - type: horizontal-stack
          cards:
          
            - type: button
              name: Включить ТВ
              show_name: false
              icon: mdi:television-classic
              show_state: false
              tap_action:
                action: call-service
                service: script.tv_switch_on

            - type: button
              name: Выключить ТВ
              show_name: false
              icon: mdi:television-classic-off
              show_state: false
              tap_action:
                action: call-service
                service: script.tv_switch_off
                
            - type: button
              name: Кинопоиск HD
              show_name: false
              icon: mdi:high-definition-box
              show_state: false
              tap_action:
                action: call-service
                service: script.tv_switch_on_kinopoisk
                
            - type: button
              name: Twitch
              show_name: false
              icon: mdi:twitch
              show_state: false
              tap_action:
                action: call-service
                service: script.tv_switch_on_twitch
                
            
  - title: Освещение
    icon: mdi:lightbulb-group
              
    cards:
    
      - type: vertical-stack
        cards:
        - type: markdown
          content: >
             **Панель переключателей** 
             
        - type: entities
          show_header_toggle: false
          entities:
            - entity: light.yeelink_light_strip_1
              name: Подсветка кровати
            - entity: light.yeelink_light_strip_2
              name: Подсветка ТВ
            - entity: light.tasmota
              name: Фитолампа
    
      - type: vertical-stack
        cards:
        - type: markdown
          content: >
             **Светильники**
              
        - type: horizontal-stack
          cards:
            - type: light
              entity: light.yeelink_light_strip_1
              name: Подсветка кровати
            - type: light
              entity: light.yeelink_light_strip_2
              name: Подсветка ТВ
            - type: light
              entity: light.tasmota
              name: Фитолампа

  - title: Железо
    icon: mdi:desktop-classic
    
    cards:
    
      - type: vertical-stack
        cards:
        
        - type: markdown
          content: >
             **Текущее состояние**
    
        - type: entities
          show_header_toggle: false
          entities:
            - entity: sensor.time
              name: Текущее время
              icon: mdi:clock-time-four-outline
            - entity: sensor.date
              name: Дата
              icon: mdi:calendar-multiselect
            
        - type: entities
          show_header_toggle: false
          entities:
            - entity: sensor.maria_db_size
              name: Объем БД
              icon: mdi:database
              
        - type: horizontal-stack
          cards:
             
            - type: gauge
              name: Загрузка CPU
              unit: '%'
              entity: sensor.processor_use_percent
              severity:
                green: 0
                yellow: 60
                red: 90
              
            - type: sensor
              name: Температура CPU
              entity: sensor.processor_temperature
              
        - type: horizontal-stack
          cards:
           
            - type: gauge
              name: Использование ОЗУ
              unit: '%'
              entity: sensor.memory_use_percent
              severity:
                green: 0
                yellow: 60
                red: 90
              
            - type: sensor
              name: Свободное место
              entity:  sensor.disk_free
            
      - type: vertical-stack
        cards:
        - type: markdown
          content: >
             **Графики** 
             
        - type: history-graph
          entities:
          - entity: sensor.maria_db_size
            name: Maria DB
            
            
  - title: Zigbee
    icon: mdi:zigbee
    
    cards:
    
      - type: vertical-stack
        cards:
        - type: markdown
          content: >
             **Уровень заряда** 
             
        - type: entities
          show_header_toggle: false
          entities:          
            - entity: sensor.battery_158d00044b636d
            - entity: sensor.battery_158d0004119b7b
            - entity: sensor.battery_158d00042df262
            
            
        - type: markdown
          content: >
             **Шлюз** 
             
        - type: entities
          show_header_toggle: false
          entities:          
            - entity: light.gateway_light_7c49eb891a1b
            - entity: sensor.illumination_7c49eb891a1b

      - type: vertical-stack
        cards:
        - type: markdown
          content: >
             **Добавление устройств**

        - type: entities
          title: Добавление Zigbee устройств
          show_header_toggle: false
          entities:
             - entity: input_boolean.zigbee_permit_join
             - entity: timer.zigbee_permit_join
             - entity: sensor.bridge_state
            
            
  - title: Погода
    icon: mdi:weather-partly-snowy-rainy
    
    cards:

      - type: weather-forecast
        entity: weather.home_assistant 
        
      - type: vertical-stack
        cards:
        - type: markdown
          content: >
             **Климат, окна двери** 
             
        - type: entities
          show_header_toggle: false
          entities:
            - entity: sensor.temperature_158d000303fea2
            - entity: sensor.temperature_158d000410c77c
            - entity: sensor.temperature_158d00044db3a0

            - entity: sensor.humidity_158d000303fea2
            - entity: sensor.humidity_158d000410c77c
            - entity: sensor.humidity_158d00044db3a0

            - entity: binary_sensor.door_window_sensor_158d00042df262
    
    